development:
 adapter: mysql2
 encoding: utf8
 database: movie_database_live
 username: root
 password: root

test:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: movie_database_live
 pool: 5
 username: root
 password: password

production:
 adapter: postgresql
 encoding: unicode
 host: localhost
 pool: 5
 database: movie_database_live
 username: root
 password: password
